name: deploy-namespace

on:
  push:
    branches:
      - master
    paths:
      - 'namespace/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save joinery-runtime
      - run: kubectl create namespace user1
